<?php
/*
 * @author    Tigren Solutions <info@tigren.com>
 * @copyright Copyright (c) 2023 Tigren Solutions <https://www.tigren.com>. All rights reserved.
 * @license   Open Software License ("OSL") v. 3.0
 *
 */

/**
 * @var Tigren\CustomerGroupRule\Block\RuleAppliedOrder $block
 */
$ruleAppliedForOrders = $block->getRulesAppliedForOrders();
?>
<!DOCTYPE html>
<html>
<head>
    <style>
        #customers {
            font-family: Arial, Helvetica, sans-serif;
            border-collapse: collapse;
            width: 100%;
        }

        .history-table td, .history-table th {
            border: 1px solid #ddd;
            padding: 8px;
        }

        .history-table tr:nth-child(even) {
            background-color: #f2f2f2;
        }

        .history-table tr:hover {
            background-color: #ddd;
        }

        .history-table th {
            padding-top: 12px;
            padding-bottom: 12px;
            text-align: left;
            background-color: #04AA6D;
            color: white;
        }
    </style>
</head>
<body>
<table class="history-table">
    <th>Rule Name</th>
    <th>Order Id</th>
    <th>Created at</th>
    <?php foreach ($ruleAppliedForOrders as $key => $item) { ?>
        <tr>
            <td><?= $item['rule_name'] ?></td>
            <td><?= $item['order_id'] ?></td>
            <td><?= $item['created_at'] ?></td>
        </tr>
    <?php } ?>
</table>
</body>
</html>
